
name: Build and Push to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: mwafa
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: mwafa/lokasiku:latest
